# Generated by Django 2.2.4 on 2024-05-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
